### PR TITLE
Parse date in 'expires' header where supplied - fixes #468

### LINKED ISSUE #468: cachingNotSpecified reports files with the Expires: header specified
The documentation seems to indicate that the 'cachingNotSpecified' metric should only report requests where the Cache-Control or Expires headers aren't specified:

> cachingNotSpecified: responses with no caching header sent (either Cache-Control or Expires)

I think this is the correct behaviour, as most browsers understand both headers and use of the Expires header is already reported in 'oldCachingHeaders'.

However, https://github.com/macbre/phantomas/blob/devel/modules/caching/caching.js seems to discard the Expires header, and therefore includes response with the Expires header set in the 'cachingNotSpecified' metric:

    case 'expires':
    case 'pragma':
    // and Varnish specific headers
    case 'x-pass-expires':
    case 'x-pass-cache-control':
        phantomas.incrMetric('oldCachingHeaders'); // @desc number of responses with old, HTTP 1.0 caching headers (Expires and Pragma)
	phantomas.addOffender('oldCachingHeaders', url + ' - ' + headerName + ': ' + value);
	break; // <-- ** no return value here **

### LINKED ISSUE #478: jQueryEventTriggers: error with jQuery 1.4.4
Hi! I have an issue on some pages since v1.9.

```
JS error: TypeError: 'undefined' is not an object (evaluating 'obj[fn]')
```
https://github.com/macbre/phantomas/blob/v1.9.0/core/scope.js#L197

This issue occurs when the page loads jQuery 1.4 when spying `jQuery.event.trigger`
https://github.com/macbre/phantomas/blob/v1.9.0/modules/jQuery/jQuery.js#L134

After this error, jQuery gets not fully loaded and several other JS errors can follow.
Page example with the issue: http://www.francetvsport.fr

### PR DESCRIPTION
**Pull request by unintelligible**
Fix for #468: cachingNotSpecified reports files with the Expires: header specified (properly formatted)

### CODE REVIEW

File: modules/caching/caching.js [hunk 1]
```diff
@@ -13,7 +13,9 @@ exports.module = function(phantomas) {
 	function getCachingTime(url, headers) {
 		// false means "no caching"
 		var ttl = false,
-			headerName;
+			headerName,
+	   		now = new Date(),
```
Comment (macbre) [inline modules/caching/caching.js]: Please use ``Date.now()`` instead

**Comment by macbre** [comment]
Please update unit tests to check this change.

Thanks for the fix!
