### PR TITLE
Fix for neverending runs

### LINKED ISSUE #846: The neverending test
Hi @macbre,

I'm currently running live a beta version of Yellow Lab Tools that uses Phantomas v2. Globally most of the pages run perfectly well 🎉. But there are a few urls (maybe one on 40) that freeze Phantomas (and YLT).

Here is one of them: https://www.premium-sales.com/

**Steps to reproduce:**
Run Phantomas as a node module with the following code:
```js
const phantomas = require("./lib/index");

const promise = phantomas(
  "https://www.premium-sales.com/",
  {
    "timeout": 60,
    "screenshot": "tmp/temp-screenshot.png"
  }
);

promise
  .then((results) => {
    console.log("Metrics", results.getMetrics());
  })
  .catch((res) => {
    console.error(res);
    console.log("Error code #%d", res.code);
    process.exit(res.code);
  });
```

**Result:**
Phantomas get stuck in a loop that keeps logging some DOM mutations related to what seems to be related to a JS animation. The browser does not throw network requests anymore, so this is not related to the `networkIdle0` option.

It rather seems to be related to screenshots. If you comment the screenshot option, Phantomas completes correctly.

Note: this problem does not happen on the CLI version of Phantomas, just the node module.

### PR DESCRIPTION
**Pull request by gmetais**
This pull request fixes two bugs that can prevent Phantomas from completing a test when testing some pages (fixes #846).

**First case:** in some cases, a CSS request's content can't be retrieved by the CSS analyzer module. The promise is never resolved, nor rejected, Phantomas is stuck in an infinite loop.

**Second case:** if saving the screenshot on the disk fails, an exception is thrown but not correctly caught and Phantomas is stuck in an infinite loop too.

And I've added test cases for both ;)

### CODE REVIEW

File: extensions/screenshot/screenshot.js [hunk 1]
```diff
@@ -40,13 +40,19 @@ module.exports = function (phantomas) {
...
+        // https://github.com/GoogleChrome/puppeteer/blob/v1.11.0/docs/api.md#pagescreenshotoptions
+        await page.screenshot(options);
 
-      phantomas.log("Screenshot stored in %s", path);
+        phantomas.log("Screenshot stored in %s", path);
+
+        // let clients know that we stored the page source in a file
+        phantomas.emit("screenshot", path);
+      } catch (err) {
+        phantomas.log("Error while taking the screenshot");
```
Comment (macbre) [inline extensions/screenshot/screenshot.js:52]: Btw, I'm wondering if there should be `phantomas.error` function...

**Review by macbre — APPROVED** [review]
And there are test, as usual :slightly_smiling_face:  Thanks!

File: extensions/screenshot/screenshot.js (hunk 1 above)
Comment (gmetais) [reply extensions/screenshot/screenshot.js:52]: I don't know. What would be the benefit? The ability to choose the log level?
